

/*se debe mandara evaluar al modelo predictivo*/


DATA SEGMENTO_2_Y_3_SCORE_1;
SET SEGMENTO_2_Y_3;
USADO=0;
KML_ANT=ULTIMO_KML ;
FECHA_APER_ANT = FECHA_ULT_VISITA;
IF PROVEEDOR="USADOS" THEN USADO=1;
IF KML_PROMEDIO=. THEN KML_PROMEDIO = PROMEDIO_KML_MES_FAMILIA;
IF KML_ANT NE . THEN KML_ESTIMADO = SUM(KML_ANT,((INTCK('DAY',FECHA_APER_ANT,TODAY()-1)/30)*KML_PROMEDIO));
IF KML_ANT = . THEN KML_ESTIMADO = ANTIGUEDAD_VEHICULO*KML_PROMEDIO;

IF FAMILIA = '' THEN DELETE;
IF KML_ANT=. THEN DELETE;
IF KML_ANT < KML_PROMEDIO THEN DELETE;

CONTRATO=0;
IF TIPO_CONTRATO NE '' THEN CONTRATO=1;
DROP ANTIGUEDAD_ENTRE_VISITAS KML_ENTRE_MANTENCION ANTIGUEDAD_HASTA_VISITA KML_ULT FECHA_APER_ULT TIPO_CONTRATO
SUCURSAL CIUDAD COMUNA PROVEEDOR PROMEDIO_KML_MES_FAMILIA DESC_CENTRO_ULT ULTIMO_KML FECHA_ULT_VISITA;
RUN;


/*NUMERO DE VECES QUE A VENIDO*/

PROC SQL;
   CREATE TABLE WORK.QUERY_FOR_INI_41(label="QUERY_FOR_INI_4") AS 
   SELECT t1.NRO_CHASSIS, 
          /* COUNT_of_NRO_CHASSIS */
            (COUNT(t1.NRO_CHASSIS)) AS COUNT_of_NRO_CHASSIS
      FROM WORK.QUERY_FOR_INI_4_0000 t1
      GROUP BY t1.NRO_CHASSIS;
QUIT;

PROC SQL;
CREATE TABLE SEGMENTO_2_Y_3_SCORE_2 AS SELECT
T1.*,
T2.COUNT_of_NRO_CHASSIS AS NRO_VISITAS_MANT
FROM SEGMENTO_2_Y_3_SCORE_1 AS T1 LEFT JOIN QUERY_FOR_INI_41 AS T2 ON (T1.NRO_CHASSIS=T2.NRO_CHASSIS);
QUIT;


/*VENTA DEL VEHICULO*/

DATA SEGMENTO_2_Y_3_SCORE_3;
SET SEGMENTO_2_Y_3_SCORE_2;
IF MONEDA_FICHA='DOLAR KAUFMANN' THEN NETO_VEHICULO_FICHA = TIPO_CAMBIO_FICHA*NETO_VEHICULO_FICHA;
DROP MONEDA_FICHA TIPO_CAMBIO_FICHA;
RUN;

/*IMPUTACION VACIOS*/

PROC SQL;
   CREATE TABLE WORK.QUERY_FOR_BASE_7 AS 
   SELECT t1.FAMILIA, 
          /* MEAN_of_NETO_VEHICULO_FICHA */
            (MEAN(t1.NETO_VEHICULO_FICHA)) FORMAT=DOLLARX20.2 AS MEAN_of_NETO_VEHICULO_FICHA
      FROM WORK.SEGMENTO_2_Y_3_SCORE_3 t1
      GROUP BY t1.FAMILIA;
QUIT;


PROC SQL;
   CREATE TABLE WORK.QUERY_FOR_PROYECTO_CLIENTES_CHIL AS 
   SELECT t1.RUT_2, 
          t1.SUMA_TRANS, 
          t1.TR_SAP, 
          t1.TR_LEGADOS, 
          t1.TR_MDLA, 
          t1.COMPRA_UNIDADES, 
          t1.COMPRA_SERVICIO, 
          t1.COMPRA_MESON, 
          t1.COMPRA_BOUTIQUE, 
          t1.OFERTAS_LEGADOS, 
          t1.COTIZA_SERVICIO, 
          t1.COTIZA_MESON, 
          t1.CANT_RECLAMOS_KAUF
      FROM CLIBDC.PROYECTO_CLIENTES_CHILE t1;
QUIT;

PROC SQL;
   CREATE TABLE WORK.SEGMENTO_2_Y_3_SCORE_4 AS 
   SELECT t1.RUT, 
          t3.SUMA_TRANS, 
          t3.TR_SAP, 
          t3.TR_LEGADOS, 
          t3.TR_MDLA, 
          t3.COMPRA_UNIDADES, 
          t3.COMPRA_SERVICIO, 
          t3.COMPRA_MESON, 
          t3.COMPRA_BOUTIQUE, 
          t3.OFERTAS_LEGADOS, 
          t3.COTIZA_SERVICIO, 
          t3.COTIZA_MESON, 
          t1.RAZON_SOCIAL, 
          t1.NRO_CHASSIS, 
          t1.NRO_VIN, 
          t1.ID_VEH, 
          t1.FEC_DOCTO_VTA, 
          t1.TERMINO_VTA, 
          t1.PATENTE, 
          t1.PROVINCIA_CLIENTE, 
          (CASE WHEN t1.NETO_VEHICULO_FICHA=. THEN T2.MEAN_of_NETO_VEHICULO_FICHA ELSE t1.NETO_VEHICULO_FICHA END) AS NETO_VEHICULO_FICHA, 
          t1.FORMA_DE_PAGO, 
          t1.FAMILIA, 
          t1.KML_ANT, 
		  t1.DESC_CENTRO_ANT,
          t1.ANTIGUEDAD_VEHICULO, 
          t1.KML_PROMEDIO, 
          t1.USADO, 
          t1.KML_ESTIMADO, 
		  t1.CONTRATO, 
          t1.NRO_VISITAS_MANT
      FROM WORK.SEGMENTO_2_Y_3_SCORE_3 t1 LEFT JOIN QUERY_FOR_BASE_7 AS T2 ON (T1.FAMILIA=T2.FAMILIA)
LEFT JOIN CLIBDC.PROYECTO_CLIENTES_CHILE AS T3 ON (T1.RUT=T3.RUT_2);
QUIT;

DATA SEGMENTO_2_Y_3_SCORE_5;
SET SEGMENTO_2_Y_3_SCORE_4;
TIPO_PERS=0;
IF  (SUBSTR(RUT,1,INDEX(RUT,"-")-1)*1) > 59000000 THEN TIPO_PERS= 1;
SCORE='X';
RUN;